name: run monthly mss plots

on:
  #schedule:
  #  - cron: '51 11 * * *'  # Runs at 11:51 UTC every day - 3:51am Pacific
  workflow_dispatch:
    
jobs:
  run-r:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Cache R packages #cache packages to make future runs faster
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: cowplot, dplyr, httr, jsonlite, tidyverse, knitr, lubridate, ggplot2, readr, stringr

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Run R script
        env:
            API_PASSWORD: ${{ secrets.API_PASSWORD }}
            API_USERNAME: ${{ secrets.API_USERNAME }}   
        run: Rscript mss_monthly_plots/mss_graphs.R
